Repository MuddCreates/hyperschedule, pull requests merged in 2019-08, with the labels that each got.

#87 Added option to grey out conflicted courses
  src/css/main.css
  src/index.html
  src/js/hyperschedule.js
Labels: waiting on response

#105 Use correct element to detect scroll changes
  src/js/hyperschedule.js
Labels: bug, performance

#92 Added conflicting courses toggle next to closed courses toggle
  src/css/main.css
  src/index.html
  src/js/hyperschedule.js
Labels: waiting on response

#110 Implement virtualized scrolling
  src/css/main.css
  src/index.html
  src/js/hyperschedule.js
Labels: bug, enhancement, feature, performance
